name: santiyemfinal
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  intl: ^0.18.1
  firebase_storage: ^11.6.4
  file_selector: ^1.0.0
  url_launcher: ^6.2.6
  supabase_flutter: ^1.10.25
  uuid: ^4.0.0
  percent_indicator: ^4.2.2
  file_picker: ^8.0.3
  path: ^1.9.0
  mime: ^1.0.5
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/data/Turkey.json
dependency_overrides:
  sign_in_with_apple:
